package team2.sofa.sofa.model;

public enum BusinessSector {
    AGRARISCH, BOUW, FINANCIEEL, ZORG, INDUSTRIE, OVERHEID_EN_ONDERWIJS, VASTGOED, RETAIL, TECH_EN_TELECOM, TRANSPORT,
    ZAKELIJKE_DIENSTVERLENING, LEEG,
}
